### ISSUE TITLE
Add documentation for singularity

### ISSUE THREAD

**Issue by prudhomm** [feelpp/book.feelpp.org#40]
Provide documentation for Feel++ singularity images
 - how to download
 - how to run applications
 - provides examples for sequential and parallel applications

**Comment by prudhomm** [comment]
@gdolle we discuss that some time ago, where does it stand ? I see nothing in the user-manual

**Comment by prudhomm** [comment]
I suggest that we discuss here first where to put the documentation, some plan and then the content

**Comment by gdolle** [comment]
The documentation in the cluster documentation for now, as it is the same usage as docker.
http://book.feelpp.org/clusters/atlas/

I need to update it since I made 2.4 changes. Also I think the install part of the user manual has to be updated from `docker` to `container` with docker and singularity subsections.

I think the installation part has to be reworked, there too many docker subsections currently, and it's clear at all for users. Also I don't think we should provide documentation for how to install docker, python, cmake etc.. it makes things too complicate.
We just add links to the real documentation for what is not feel++ to keep things simple.

The install plan should be only

- Requirements
- Containers
  - Docker
  - Singularity
- Linux
- Mac
- (Windows)
- From sources

And update the Using Feel++ which is empty currently. And put there how to use the previous install.

I'll rework some parts and PR.

**Comment by prudhomm** [comment]
the user manual, see #48, is still broken in my opinion. Maybe some docs are not necessary as you say but there are various links across the board that are now dangling. I think these docs are useful but they could be placed somewhere else. There is definitely a problem with the current structure.

**Comment by gdolle** [comment]
Yes necessary information is there to use it. We can open a new issue after user feedback, if it's not clear enough.
