### ISSUE TITLE
Review User Manual

### ISSUE THREAD

**Issue by prudhomm** [feelpp/book.feelpp.org#48]
review the user manual and proposes fixes, modifications, additions...
http://docs.feelpp.org/user/0.1/index.html

 - [ ] Does it answer basic questions about Feel++?
 - [ ] Does it provide proper installation procedures?
 - [ ] Does it provide basic examples?
 - [ ] Does it enable a quick start with Feel++? (within 1 hour counting software download)

**Comment by prudhomm** [comment]
We want to improve to user experience (UX) to start with Feel++

**Comment by prudhomm** [comment]
The user manual needs really some love. The information there is not straightforward, we need a script that hides all the gory `docker`/`singularity` details I think.
something like 
```
feelpp run -c [docker|singularity] <cmd>
```
without `<cmd>` we would enter the `docker|singularity` shell
this should be as simple as possible. It would hide the details and we wouldn't have to update the documentation each time we add some new feature or variable.

Also **Get Feel++** menu really needs to get improved and reorganized, well everything needs some rework.

**Comment by gdolle** [comment]
Hum, I agree that it's not yet straightforward and that we need to factor the documentation to be more clear. (And all documentation need reworks).

But I don't agree that a one command for all container is a good idea even if it can looks nice at first sight; If we provide a command, it means that we have to provide maintain it and provide support:
The time we earn at maintaining the documentation, we lose it at explaining to people how to use our command (which actually just redo what docker/singularity already does very well...). Which will be the case since we blackboxed container systems... 
=> Gory user documentation details becomes then gory dev maintaining/support.

I'd prefer we provide links to our containers and links to container system documentations and that's all. For any container relative questions, we redirect people to singularity/docker documentation/forum.

Then we can finally focus on having a proper documentation about how to compile/use a Feel++ application when it is properly installed in a UNIX standard manner(=> this way you can use the documentation for all cases: container, package, etc...).

**Comment by prudhomm** [comment]
I have created feelpp/feelpp#1136 for the Feel++ shell. I will make a prototype. For end-users, it is currently way too complicated and the various `-v` `-e` options are not important for the user. He/she just have to know that the results will be in `$HOME/feel`, the rest is just an internal recipe.

**Comment by gdolle** [comment]
I still don't agree with that see https://github.com/feelpp/book.feelpp.org/issues/48#issuecomment-377690325. 
They are better way to simplify usage for end-users. We could provide then a Cloud link that connect them directly in containers (on AMAZON web service or else), and focus on usage in the container...

**Comment by prudhomm** [comment]
what is a Cloud link? in my mind it is not very complicated what I propose. the objective is to simplify the command line. I fail to see currently what you are proposing

**Comment by gdolle** [comment]
For example on this kind of service https://aws.amazon.com/fr/ecs. We could propose for training directly the application via the container. Or in a shell environment.
(And user can test for free EC2 instance)

**Comment by prudhomm** [comment]
I think this is a good state now for the release. unless there is a pressing/important I would like to close this
